### ISSUE TITLE
do not work with Big Sur and APFS

### ISSUE THREAD

**Issue by wolfogre** [nlfiedler/timedog#17] opened 2020-11-17 13:00 UTC
```text
$ timedog
None or only one Time Machine backups found at /usr/local/bin/timedog line 197.
```

![image](https://user-images.githubusercontent.com/9418365/99393119-d46f9080-2917-11eb-923e-52810a847db0.png)

**Comment by Maxim-Inv** [comment] 2020-11-18 08:40
The same issue

**Comment by nlfiedler** [comment] 2020-11-20 17:01
I don't have BigSur yet, but when I do, I'll take a look. Thanks for the report.

**Comment by bermudalocket** [comment] 2021-01-26 18:18
> I don't have BigSur yet, but when I do, I'll take a look. Thanks for the report.

Hey @nlfiedler, any update on this? I can take a look myself if you are preoccupied with other projects :)

**Comment by nlfiedler** [comment] 2021-01-27 02:01
@bermudalocket I will update to Big Sur in the next week or so, at which point I can try to reproduce this. However, don't let that stop you from trying it yourself. I welcome any help you can offer. Thanks.

**Comment by michaelvandorpe** [comment] 2021-03-14 12:08
Same issue here, and also using Big Sur and APFS.

**Comment by nlfiedler** [comment] 2021-03-15 20:45
Sorry it's taken me so long to finally try this out. The version of timedog from commit 12947dd works fine for me with Big Sur backing up an APFS-formatted SSD to an HFS-formatted external drive. Ironically, with commit 3848923 I now see the `None or only one Time Machine backups found` error. So, the fix worked in reverse for me. I suspect there are idiosyncrasies with Time Machine and getting it just right is rather difficult.

**Comment by antimirov** [comment] 2021-03-15 20:51
I'm backing my data to a network SMB share on a Synology NAS, the whole volume there is BTRFS.

**Comment by antimirov** [comment] 2021-03-16 08:18
So what are the directories you have in that /Volumes/ backups directory? We may include several patterns to support different schemas.

**Comment by michaelvandorpe** [comment] 2021-03-16 08:27
@nlfiedler you are backing up *to* an HFS-formatted external drive. For me, the problem is with backing up *from* an APFS internal drive *to* an external APFS external drive. Not sure whether that's worth pointing out... 

michael@MacBook-Pro Time Machine 2TB % ls
2021-03-15-214154.previous	backup_manifest.plist
2021-03-16-092234.inprogress

**Comment by nlfiedler** [comment] 2021-03-17 04:14
Here's the truncated listing:

```
$ ls -l /Volumes/TMbackup/Backups.backupdb/kuro
...
drwxr-xr-x@  - root 16 Mar 20:13 2021-03-16-201300
drwxr-xr-x@  - root 16 Mar 21:12 2021-03-16-211253.inProgress
lrwxr-xr-x  17 root 16 Mar 20:13 Latest -> 2021-03-16-201300
```

**Comment by pfahlstrom** [comment] 2021-03-18 17:08
I have the same issue. I mounted the backup sparsebundle from the NAS, and in /Volumes I saw:

Time Machine Backups

I ran timedog and it said:

None or only one Time Machine backups found at /usr/local/bin/timedog line 197

Now in /Volumes I see both:

Time Machine Backups
Time Machine Backups 1

Both of them contain only 2 files via ls:

2021-03-18-101627.previous
backup_manifest.plist

However in the Finder there is only one Time Machine Backups volume visible, and it contains 32 different backup files, similar to wolfogre's screenshot above. Running tmutil listbackups also shows the 32 backup files. I don't know why ls isn't showing them.

**Comment by nlfiedler** [comment] 2021-03-20 00:45
Set up a new mini and APFS-formatted backup disk, and yes, `tmutil` behaves strangely and any attempt at listing the TM volume proves to be futile. Apple has made TM really weird now, I suspect doing anything beyond using their basic graphical interface is just asking for trouble.

**Comment by antimirov** [comment] 2021-03-20 22:13
Yep, yesterday it just refused to connect to my NAS share with some authentication error. It took one week and a minor macOS update to achieve this, just great.

**Comment by rossburton** [comment] 2021-04-01 09:28
Latest timedog, latest Big Sur backing up over the network.  Can't seem to make it work...

**Comment by warmup72** [comment] 2021-05-05 20:25
After my update to Big Sur yesterday, I am shocked that timedog no longer works with APFS. Is there any chance that it will get back to normal?

**Comment by dennisbirch** [comment] 2021-07-10 16:29
I am running Big Sur on a 2019 MacBook Pro with Time Machine on an external drive attached via USB. Timedog has been working just fine for me the several times I've tried it in the last couple of days (to investigate why my backups have recently gotten so huge).

**Comment by warmup72** [comment] 2021-07-10 18:36
Since Timedog doesn´t work I use Backuploupe.
SOu can try it, but do see what ™ does i think you must buy a licence. But ist really good

**Comment by gingerbeardman** [comment] 2022-02-03 22:52
+1

nothing new to add to what has been said before.

**Comment by huyz** [comment] 2022-04-18 14:44
Same thing on Monterey (Apple Silicon) with an APFS Time Machine volume.

**Comment by kschmid** [comment] 2022-05-27 09:16
For me it works well on local USB-Drive, but could not get it to work with Synology NAS. If the USB-Drive is not mounted, I get the same error message. (M1, Monterey).

**Comment by arekkusu42** [comment] 2024-03-15 05:26
I had the same problem in Sonoma 14.4, backing up an M3 MBP to an old HFS-formatted Time Capsule.

In my setup, "tmutil machinedirectory" returns "/Volumes/Backup of \<boot partition\>" which only contains a single YYYY-MM-DD-HHMMSS.previous.  The actual incremental backups are stored on the hidden /Volumes/.timemachine/\<UUID\>/  which timedog fails to locate.

I modified my timedog to work, by removing the `tmutil machinedirectory` query and replacing it with `tmutil listbackups -m` which forces the backup volume to be mounted.  This also removes timedog's -D option.  I have not tested this on older setups, so YMMV.
[timedog.zip](https://github.com/nlfiedler/timedog/files/14611232/timedog.zip)

**Comment by varenc** [comment] 2024-03-28 22:49
@arekkusu42  your fork gave me some success! Thanks.

**Comment by nlfiedler** [comment] 2024-03-30 17:45
Thank you for tracking down the fix for this, I've committed the change. I'm going to mark this issue as closed. If anyone finds that the issue has returned, feel free to open a new issue with details. Thank you.

**Closed by nlfiedler** 2024-03-30 17:45 UTC

**Comment by uPaymeiFixit** [comment] 2026-02-06 04:44
Admittedly I haven't read through every comment or fully understood why this is happening, but I can tell you I was having the same `None or only one Time Machine backups found` error, and running @arekkusu42's fork fixed it. I would be happy to provide any additional details if needed, just let me know what you'd like to know.
